apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: intel
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://intel.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-gpu-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: nfd
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
  chart:
    spec:
      chart: intel-device-plugins-operator
      sourceRef:
        kind: HelmRepository
        name: intel
      version: ">=0.30.0"
  interval: 1h0m0s
  releaseName: intel-gpu-operator
  targetNamespace: default
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    sharedDevNum: 1
    logLevel: 2
    resourceManager: false
    enableMonitoring: true
    allocationPolicy: "none"
