apiVersion: v1
kind: Pod
metadata:
  name: intelgpu-test
  namespace: default
spec:
  containers:
  - command:
    - clinfo
    image: kangwarn/intel-opencl-icd:latest
    imagePullPolicy: Always
    name: intel-opencl-icd
    resources:
      limits:
        gpu.intel.com/i915: "1"
      requests:
        gpu.intel.com/i915: "1"
  restartPolicy: Never
status: {}
