apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nvidia-gpu-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvidia
  namespace: nvidia-gpu-operator
spec:
  interval: 1h0m0s
  url: https://helm.ngc.nvidia.com/nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: nvidia-gpu-operator
spec:
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia
  interval: 1h0m0s
  timeout: 10m0s
  releaseName: nvidia-gpu-operator
  targetNamespace: nvidia-gpu-operator
