---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBhnKPnz4ekaaprmDWMwvK1/iYh2evD2DR6iMIa1XsBcLYR9hPa5h8jdzBuFrfHIaGlUknyFl2Df/SzWtk/05UFHjjztV3iUoHFh4eprzfy+AxB+Vt5jpUXu+8N/NivyDpIKFIO/0YCHRmEJG4Qc00g+shXMfnNulAZJBD3BfJUu3Uf2iLS3rDhk0UTZ+lroMP7s9+NlZrWw8jFA2+5/RGn6yezad6kXRP4L6D0GAP/BdbCHC2OJ7pdxNPysZApFBs1CsrA7AnTK4eb/HBkaogfJf7BXKfZyg+341KTybZd+HLs/99bZCR05ykvcU1XQmqfhp/Ea9jeJhrRwtI2yA4sBh7Hol1FgoMJGPgmSDdzMFjprmF7E+uShkwQ2UmQr8ERGk7zGnQsHGDxj5TTLQH0EcTS3NtjqZoe+jZeYOZxJNci0plzI4tjk0xbwNOsCylJ9A+okOYxR3OpnIeGb98BJSYNiTCWZvqX2OnD0v0gPJqbUkch9inxYOKUGI6wSkwRRa+0AUo/wV8Gj507JRd45G/ir1qbF9TWYVVS+BiL+iGhQtg+v6Cde7g1MsTC2FUgXoR44URZwD3VLuGWlDmUA77uRrwXdNEi4Mb4qDtSeBHroq1A4U6lyOOl5tIQ6gpy/KRAp4Yg2EXugdqIDW4fqlyO1ml0dt6sKg9OCpgtOkhA07My2z7bZ5ZQzLO9F9/Qbmp84HwhCJM=
    user: AgChDPtiHXey4jblyjkThBgQjK/41UgOjCWDXDXKFucURmnw7VyBAKsw5UzvJ/pzj+CFt4g1NCvK4gXQt6vMup1wTOEolYFzilfu24rrd+Z8JOj57gx1DVtDGNAfLDbMFr/v7TLEeFiF9BnC5yj5RypABKLSa9soNTG9FUaWpk8iJM1W9dU4rxHBG+vAxeEL546HVY+WtUCmNnrO6T2yY5BZHsNFccrPan6cec3JxrBlZPdLDh830lRUM9On1JAT2l+KMsLeyTGXk9ZJ2e/bvTAohuFrGCKCaZcPN3D3jlfZGTqY0ci/+4khfcM9IuTmh2LgnP0mLo5s2jNh+OwMtmiPOFVj3yqBdHt9A1yHQidfGxU1LY4HLag1SuiAdJxjsAqfwh/znw8ySKiW5p3luGRQA+fp2GfS+Zb8gPiobE75wXO/puai4NYKBjNmQJCirai/VdgvutFheo3CsAKnfkoBUUMyvsg9KWdeKEhGsokdZba90dE/pqV7bR4PKaf7SCQ7a6wccmWlJwivbkvF9d67iId2vLRlqFKXB5mgIyr8ybUDjO4+sFQ5Ftky6hPF2FEWRn+SvAFkz6HEI0f7XrmNBBP/l8+RL5WLbKcOr+ijVzGtEsE2PB7tp7SgKmf5oE/byxsRy7cmxwIgyolmRw5C9VTGMZRPV+GxgU/rD0eulN1hYvNsR59aMCbukO3Jc2AjQ9gK+g==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
