apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client
  name: client
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
    image: busybox
    name: client
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
