---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  patches:
    - patch: |-
        apiVersion: autoscaling/v2beta2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo
        spec:
          minReplicas: 2             
      target:
        name: podinfo
        kind: HorizontalPodAutoscaler
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: podinfo
        spec:
          type: NodePort
          ports:
            - name: http
              port: 9898
              protocol: TCP
              targetPort: http
              nodePort: 30098
            - name: grpc
              port: 9999
              protocol: TCP
              targetPort: grpc
              nodePort: 30099
      target:
        name: podinfo
        kind: Service
