apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../00-ecs-config.yaml
  - ../10-ns.yaml
  - ../20-pv.yaml
  - ../30-prometheus.yaml
  - ../40-grafana-cm.yaml
  - ../50-grafana.yaml
